"""LLM-readable provider queues for owner-question discussion."""
from __future__ import annotations

from pathlib import Path

from ..config import Config
from ..discussion_queue import PROVIDERS, read_discussion_queue
from ..model import Graph, owner_question_fingerprint
from .common import item_link, source_link_prefix


def render(graph: Graph, cfg: Config, root: Path) -> dict[str, str]:
    queue, warnings = read_discussion_queue(cfg, root, graph, strict=False)
    prefix = source_link_prefix(cfg, root)
    by_id = graph.item_map()
    questions = {}
    for question in graph.owner_questions:
        questions.setdefault(question.story_id, []).append(question)
    lines = [
        "# Discussion queue",
        "",
        "Generated, LLM-readable coordination view. Read your provider lane top-first at session start. "
        "Queued does not mean discussed, answered, or applied; do not edit this file.",
        "",
    ]
    if queue is None:
        lines.extend([f"> {warning}" for warning in warnings])
        lines.append("")
        queue = {"revision": 0, "updatedAt": None, "queues": {p: [] for p in PROVIDERS}}
    lines.append(
        f"Queue revision: **{queue['revision']}** · updated: `{queue.get('updatedAt') or 'never'}`"
    )
    lines.append("")
    for provider in PROVIDERS:
        lines.extend([f"## {provider.title()}", ""])
        lane = queue["queues"][provider]
        if not lane:
            lines.extend(["No Stories queued for discussion.", ""])
            continue
        for position, story_id in enumerate(lane, 1):
            item = by_id[story_id]
            current = sorted(questions.get(story_id, []), key=lambda value: value.id)
            state = f"{len(current)} open question{'s' if len(current) != 1 else ''}"
            if not current:
                state = "general Story discussion · no open owner questions"
            lines.append(f"{position}. {item_link(item, prefix)} — **{state}**")
            for question in current:
                lines.append(
                    f"   - `{question.id}` — {question.prompt} "
                    f"(fingerprint `{owner_question_fingerprint(question)[:12]}`)"
                )
        lines.append("")
    return {"discussion-queue.md": "\n".join(lines).rstrip() + "\n"}
