"""Dependency-ordered roadmap renderer."""
from __future__ import annotations

from pathlib import Path

from ..config import Config
from ..model import Graph, Item
from .common import item_link, source_link_prefix, status_cell, topo


def _planned(item: Item) -> bool:
    return not item.id.startswith(("phase:", "todo:"))


def _tail(item_id: str) -> str:
    return item_id.split(":", 1)[-1].split("/")[-1]


def _deps_cell(item: Item) -> str:
    value = ", ".join(_tail(dep) for dep in item.deps) or "—"
    return value if len(value) <= 80 else value[:79] + "…"


def _section(
    title: str,
    items: list[Item],
    graph: Graph,
    cfg: Config,
    group_titles: dict[str, str],
    prefix: str,
) -> list[str]:
    lines = [f"## {title}", "", "| # | Status | Item | Group | Deps |",
             "|---:|---|---|---|---|"]
    all_deps = {item.id: item.deps for item in graph.items}
    for number, item in enumerate(topo(items, all_deps), 1):
        group = group_titles.get(item.group or "", "—")
        lines.append(
            f"| {number} | {status_cell(cfg, item.status)} | {item_link(item, prefix)} "
            f"| {group} | {_deps_cell(item)} |"
        )
    lines.append("")
    return lines


def render(graph: Graph, cfg: Config, root: Path) -> dict[str, str]:
    prefix = source_link_prefix(cfg, root)
    vocab = graph.vocab.get("statuses", cfg.vocab["statuses"])
    legend = " · ".join(f"{status.get('emoji', '❔')} {status.get('name', 'unknown')}"
                        for status in vocab)
    lines = [
        "# Roadmap (dependency-ordered release waves)",
        "",
        "_Generated by vizzer._",
        "",
        f"**Legend:** {legend}",
        "",
    ]

    planned = [item for item in graph.items if _planned(item)]
    releases = list(cfg.get("render.releases", []))
    group_titles = {group.id: group.title for group in graph.groups}
    for release in releases:
        release_items = [item for item in planned if item.release == release]
        if release_items:
            lines.extend(
                _section(release, release_items, graph, cfg, group_titles, prefix)
            )

    configured = set(releases)
    unscheduled = [item for item in planned if item.release not in configured]
    lines.extend(
        _section("Unscheduled", unscheduled, graph, cfg, group_titles, prefix)
    )
    return {"roadmap.md": "\n".join(lines)}
